                                                                                                                                                                                                                                                               
Delivered-To: sean.fioritto@gmail.com
Received: by 10.14.119.201 with SMTP id n49cs10151eeh;
        Sat, 3 Jul 2010 11:36:02 -0700 (PDT)
Return-Path: <3EYMvTBQKABAw44w1uq1u798-347u51Ew44w1u.s42@alerts.bounces.google.com>
Received-SPF: pass (google.com: domain of 3EYMvTBQKABAw44w1uq1u798-347u51Ew44w1u.s42@alerts.bounces.google.com designates 10.100.131.18 as permitted sender) client-ip=10.100.131.18;
Authentication-Results: mr.google.com; spf=pass (google.com: domain of 3EYMvTBQKABAw44w1uq1u798-347u51Ew44w1u.s42@alerts.bounces.google.com designates 10.100.131.18 as permitted sender) smtp.mail=3EYMvTBQKABAw44w1uq1u798-347u51Ew44w1u.s42@alerts.bounces.google.com; dkim=pass header.i=3EYMvTBQKABAw44w1uq1u798-347u51Ew44w1u.s42@alerts.bounces.google.com
Received: from mr.google.com ([10.100.131.18])
        by 10.100.131.18 with SMTP id e18mr621505and.21.1278182161611 (num_hops = 1);
        Sat, 03 Jul 2010 11:36:01 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=google.com; s=beta;
        h=domainkey-signature:mime-version:received:list-unsubscribe:list-id
         :message-id:date:subject:from:to:content-type
         :content-transfer-encoding;
        bh=3+3/Ztzz7Ts6rZt+27x9YxynECnKA6SEx+ou1JN3E70=;
        b=tC6R7+MLd32y+ojtycwneRaTuK3XVeQw/2vtY14Z/as5/0BGyDL3mYpOlS7K22obJn
         ceocaAu8AmIpCqcNLsfg==
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=google.com; s=beta;
        h=mime-version:list-unsubscribe:list-id:message-id:date:subject:from
         :to:content-type:content-transfer-encoding;
        b=lgYU8+zK5aTRgA9ijeywW2TNTSZeTmn9lYefeuDvL0M46do7tXdp3pamttHtpR2J+d
         MB9sW+oUxdVR06ZgciIg==
MIME-Version: 1.0
Received: by 10.100.131.18 with SMTP id e18mr451663and.21.1278182161552; Sat, 
	03 Jul 2010 11:36:01 -0700 (PDT)
List-Unsubscribe: <mailto:ur@unsubscribe.alerts.google.com?subject=AB2Xq4jsDy4ienBZYuYgWbzBWQ5i6LiD5L4y8JY>
List-Id: <AB2Xq4jsDy4ienBZYuYgWbzBWQ5i6LiD5L4y8JY.alerts.google.com>
Message-ID: <0016e6434aeeb29447048a7ff92e@google.com>
Date: Sat, 03 Jul 2010 18:36:01 +0000
Subject: Google Alert - barack obama
From: Google Alerts <googlealerts-noreply@google.com>
To: sean.fioritto@gmail.com
Content-Type: text/html; charset=windows-1252
Content-Transfer-Encoding: quoted-printable


<html><head></head><body><div style=3D"font-family: arial,sans-serif; width=
: 600px"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"6=
00px"><tr><td style=3D"background-color:#EBEFF9; padding: 4px 8px 4px 8px">=
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"100%"><tr>=
<td><font size=3D"-1"><nobr><b>News</b></nobr></font></td><td width=3D"70%"=
 align=3D"right"><font size=3D"-1"><b>26</b> new results for <b>barack obam=
a</b></font></td></tr></table></td></tr><tr><td>&nbsp;</td></tr><tr><td sty=
le=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #1111CC" href=3D"http:=
//www.google.com/url?sa=3DX&amp;q=3Dhttp://www.foxnews.com/politics/2010/07=
/03/obama-announces-b-grants-clean-energy-jobs/&amp;ct=3Dga&amp;cad=3D:s7:f=
1:v1:i0:lt:e0:p0:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNGcLm8h0E=
3iyj0m0IBNYyDSBP94Xg"><b>Obama</b> Announces $2B in Grants for Clean Energy=
 Jobs</a><br><font size=3D"-1"><font color=3D"#777777">FOXNews</font><br>Pr=
esident <b>Barack Obama</b> is pictured on board Air Force One as he travel=
s from Andrews Air Force Base, Md., to Yeager Airport in Charleston, W.Va.,=
 Friday, <b>...</b><br><a style=3D"color: #228822" href=3D"http://www.googl=
e.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%3Fncl%3Dhttp://w=
ww.foxnews.com/politics/2010/07/03/obama-announces-b-grants-clean-energy-jo=
bs/%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e0:p0:t1278182161:&amp;=
cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNFbIIlYqaWQy7xx3hEVPMpV2el79A" title=3D"htt=
p://news.google.com/news/story?ncl=3Dhttp://www.foxnews.com/politics/2010/0=
7/03/obama-announces-b-grants-clean-energy-jobs/&amp;hl=3Den">See all stori=
es on this topic &raquo;</a></font></td></tr><tr><td style=3D"padding: 0px =
8px 16px 8px;"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" widt=
h=3D"100%"><tr><td valign=3D"top"><a style=3D"color: #1111CC" href=3D"http:=
//www.google.com/url?sa=3DX&amp;q=3Dhttp://www.chicagotribune.com/news/loca=
l/blagojevich/ct-met-blagojevich-trial-0704-20100704,0,3385819.story&amp;ct=
=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e1:p1:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp=
;usg=3DAFQjCNHrITvc9Nnnxrbz_P_zKn18dcdYzw">Audio reveals swipes at <b>Obama=
</b>, other Illinois Democrats</a><br><font size=3D"-1"><font color=3D"#777=
777">Chicago Tribune</font><br>As such, Jones is no longer &quot;a very ins=
piring thought&quot; to be a pick to replace <b>Barack Obama</b> in the US =
Senate. Still, Blagojevich continued, Jones &quot;can raise <b>...</b><br><=
a style=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=
=3Dhttp://news.google.com/news/story%3Fncl%3Dhttp://www.chicagotribune.com/=
news/local/blagojevich/ct-met-blagojevich-trial-0704-20100704,0,3385819.sto=
ry%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e1:p1:t1278182161:&amp;c=
d=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHokr7ttrNrodJNbUjhIyOwPMZuZA" title=3D"http=
://news.google.com/news/story?ncl=3Dhttp://www.chicagotribune.com/news/loca=
l/blagojevich/ct-met-blagojevich-trial-0704-20100704,0,3385819.story&amp;hl=
=3Den">See all stories on this topic &raquo;</a></font></td><td align=3D"ce=
nter" width=3D"80" valign=3D"top"><a href=3D"http://www.google.com/url?sa=
=3DX&amp;q=3Dhttp://www.chicagotribune.com/news/local/blagojevich/ct-met-bl=
agojevich-trial-0704-20100704,0,3385819.story&amp;ct=3Dga&amp;cad=3D:s7:f1:=
v1:i0:li:e1:p1:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHrITvc9Nnn=
xrbz_P_zKn18dcdYzw"><img border=3D"0" src=3D"http://nt2.ggpht.com/news/tbn/=
1kR4zpW4oKgJ" alt=3D"" width=3D"80" height=3D"62"></a><font size=3D"-2"><br=
><a href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.chicagotrib=
une.com/news/local/blagojevich/ct-met-blagojevich-trial-0704-20100704,0,338=
5819.story&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lic:e1:p1:t1278182161:&amp;cd=
=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHrITvc9Nnnxrbz_P_zKn18dcdYzw">Chicago Tribun=
e</a></font></td></tr></table></td></tr><tr><td style=3D"padding: 0px 8px 1=
6px 8px;"><a style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=
=3DX&amp;q=3Dhttp://www.chicagotribune.com/news/columnists/ct-oped-0704-pag=
e-20100704,0,4670234.column&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e2:p2:t12=
78182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNFUwqLRIkBlTBd3I7eAhfynCSQL3A=
">Reform deferred</a><br><font size=3D"-1"><font color=3D"#777777">Chicago =
Tribune</font><br>On the thorny issue of immigration, &quot;this administra=
tion will not just kick the can down the road,&quot; says President <b>Bara=
ck Obama</b> =97 after almost a year and a <b>...</b><br><a style=3D"color:=
 #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.goog=
le.com/news/story%3Fncl%3Dhttp://www.chicagotribune.com/news/columnists/ct-=
oped-0704-page-20100704,0,4670234.column%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s=
7:f1:v1:i0:lr:e2:p2:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNEZ6wI=
ljbaFL00Ah030xM3tE2m61A" title=3D"http://news.google.com/news/story?ncl=3Dh=
ttp://www.chicagotribune.com/news/columnists/ct-oped-0704-page-20100704,0,4=
670234.column&amp;hl=3Den">See all stories on this topic &raquo;</a></font>=
</td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #=
1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.google.=
com/hostednews/ap/article/ALeqM5iJfKyF4dmzX9mGbFD8GBKIjs1rWwD9GN7TKG0&amp;c=
t=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e3:p3:t1278182161:&amp;cd=3D4Ya67t6E3e4&am=
p;usg=3DAFQjCNHR2gJz3tAu9iQ_o5JlUBc_4nnqfA">GOP chairman: Afghan &#39;war o=
f <b>Obama&#39;s</b> choosing&#39;</a><br><font size=3D"-1"><font color=3D"=
#777777">The Associated Press</font><br>In remarks captured Thursday on cam=
era and posted online, Steele criticized President <b>Barack Obama</b> and =
his handling of the Afghan war and suggested the war <b>...</b><br><a style=
=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp:/=
/news.google.com/news/story%3Fncl%3Dhttp://www.google.com/hostednews/ap/art=
icle/ALeqM5iJfKyF4dmzX9mGbFD8GBKIjs1rWwD9GN7TKG0%26hl%3Den&amp;ct=3Dga&amp;=
cad=3D:s7:f1:v1:i0:lr:e3:p3:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQ=
jCNGaUT4uoPrdsWlrE0lBbn3vono04A" title=3D"http://news.google.com/news/story=
?ncl=3Dhttp://www.google.com/hostednews/ap/article/ALeqM5iJfKyF4dmzX9mGbFD8=
GBKIjs1rWwD9GN7TKG0&amp;hl=3Den">See all stories on this topic &raquo;</a><=
/font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a style=3D"co=
lor: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.j=
post.com/IranianThreat/News/Article.aspx%3Fid%3D180308&amp;ct=3Dga&amp;cad=
=3D:s7:f1:v1:i0:lt:e4:p4:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCN=
GGTNLyIXP2cmuunb8TdwvG82JZYA">Ahmadinejad: New sanctions &#39;pathetic&#39;=
</a><br><font size=3D"-1"><font color=3D"#777777">Jerusalem Post</font><br>=
<b>...</b> &quot;pathetic&quot; on Saturday in his first speech since the n=
ew measures were signed into law by US President <b>Barack Obama</b> on Thu=
rsday, Reuters reported. <b>...</b><br><a style=3D"color: #228822" href=3D"=
http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%=
3Fncl%3Dhttp://www.jpost.com/IranianThreat/News/Article.aspx%253Fid%253D180=
308%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e4:p4:t1278182161:&amp;=
cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNFVcBHq_IKQ7MiER2Tq9DHY29_PQQ" title=3D"htt=
p://news.google.com/news/story?ncl=3Dhttp://www.jpost.com/IranianThreat/New=
s/Article.aspx%3Fid%3D180308&amp;hl=3Den">See all stories on this topic &ra=
quo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a st=
yle=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhtt=
p://news.bbc.co.uk/1/hi/programmes/from_our_own_correspondent/8782988.stm&a=
mp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e5:p5:t1278182161:&amp;cd=3D4Ya67t6E3e=
4&amp;usg=3DAFQjCNFuu8BOrN02A8q9J-XbxdhvN4ek2A">Israel&#39;s rocky friendsh=
ip with <b>Barack Obama</b></a><br><font size=3D"-1"><font color=3D"#777777=
">BBC News</font><br>It is safe to say that Mr Netanyahu&#39;s relations wi=
th President <b>Obama</b> have been disastrous. Unlike his predecessor, Mr =
<b>Obama</b> believes that some of Israel&#39;s <b>...</b><br><a style=3D"c=
olor: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news=
.google.com/news/story%3Fncl%3Dhttp://news.bbc.co.uk/1/hi/programmes/from_o=
ur_own_correspondent/8782988.stm%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:=
i0:lr:e5:p5:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNEsNtivWbLZVO9=
k11zTUKZR1rrOLA" title=3D"http://news.google.com/news/story?ncl=3Dhttp://ne=
ws.bbc.co.uk/1/hi/programmes/from_our_own_correspondent/8782988.stm&amp;hl=
=3Den">See all stories on this topic &raquo;</a></font></td></tr><tr><td st=
yle=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #1111CC" href=3D"http=
://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.foxnews.com/opinion/2010/07=
/02/craig-shirley-ranking-americas-presidents-ronald-reagan-better-barack-o=
bama/&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e6:p6:t1278182161:&amp;cd=3D4Ya=
67t6E3e4&amp;usg=3DAFQjCNHdwwpWO87aBUZMKJcTlGhKXQyYpQ"><b>Barack Obama</b> =
A Better President than Reagan? No Chance</a><br><font size=3D"-1"><font co=
lor=3D"#777777">FOXNews</font><br>Surely the bias of those surveyed was und=
erscored with the nonsensical ranking of <b>Barack Obama</b> ahead of Ronal=
d Reagan. First, Obama should not have even <b>...</b><br><a style=3D"color=
: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.goo=
gle.com/news/story%3Fncl%3Dhttp://www.foxnews.com/opinion/2010/07/02/craig-=
shirley-ranking-americas-presidents-ronald-reagan-better-barack-obama/%26hl=
%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e6:p6:t1278182161:&amp;cd=3D4Ya=
67t6E3e4&amp;usg=3DAFQjCNFqIII29c24XHjR224qNiy0IIkClw" title=3D"http://news=
.google.com/news/story?ncl=3Dhttp://www.foxnews.com/opinion/2010/07/02/crai=
g-shirley-ranking-americas-presidents-ronald-reagan-better-barack-obama/&am=
p;hl=3Den">See all stories on this topic &raquo;</a></font></td></tr><tr><t=
d style=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #1111CC" href=3D"=
http://www.google.com/url?sa=3DX&amp;q=3Dhttp://sify.com/news/gaga-beats-ob=
ama-in-facebook-fans-record-news-international-khdw4ccjbgi.html&amp;ct=3Dga=
&amp;cad=3D:s7:f1:v1:i0:lt:e7:p7:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=
=3DAFQjCNHQEDBkOgPlh0PnUFmo8zOSIoaAFQ">Gaga beats <b>Obama</b> in Facebook =
fans record</a><br><font size=3D"-1"><font color=3D"#777777">Sify</font><br=
>Pop star Lady Gaga has beaten US President <b>Barack Obama</b> to top the =
number of fans on social networking site Facebook. The &#39;Poker Face&#39;=
 singer&#39;s fan count <b>...</b><br><a style=3D"color: #228822" href=3D"h=
ttp://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%3=
Fncl%3Dhttp://sify.com/news/gaga-beats-obama-in-facebook-fans-record-news-i=
nternational-khdw4ccjbgi.html%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:=
lr:e7:p7:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNEg4tyOvFeKig2QH-=
mo8xGCxEwCEw" title=3D"http://news.google.com/news/story?ncl=3Dhttp://sify.=
com/news/gaga-beats-obama-in-facebook-fans-record-news-international-khdw4c=
cjbgi.html&amp;hl=3Den">See all stories on this topic &raquo;</a></font></t=
d></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #111=
1CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.reuters.co=
m/article/idUSTRE6614AE20100702%3Ftype%3DpoliticsNews&amp;ct=3Dga&amp;cad=
=3D:s7:f1:v1:i0:lt:e8:p8:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCN=
GmNirjBTdpHlzlvHCa9-vR40t6vg"><b>Obama</b> signs 3-month extension of homeb=
uyer credit</a><br><font size=3D"-1"><font color=3D"#777777">Reuters</font>=
<br>By Corbett B. Daly WASHINGTON (Reuters) - President <b>Barack Obama</b>=
 on Friday signed a law giving consumers already in the process of buying a=
 home three extra <b>...</b><br><a style=3D"color: #228822" href=3D"http://=
www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%3Fncl%3=
Dhttp://www.reuters.com/article/idUSTRE6614AE20100702%253Ftype%253Dpolitics=
News%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e8:p8:t1278182161:&amp=
;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHgoc7lTnpC0ojApibZR0T14z4Mpg" title=3D"ht=
tp://news.google.com/news/story?ncl=3Dhttp://www.reuters.com/article/idUSTR=
E6614AE20100702%3Ftype%3DpoliticsNews&amp;hl=3Den">See all stories on this =
topic &raquo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8p=
x;"><a style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&am=
p;q=3Dhttp://online.wsj.com/article/BT-CO-20100702-709057.html&amp;ct=3Dga&=
amp;cad=3D:s7:f1:v1:i0:lt:e9:p9:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=
=3DAFQjCNHx281EK10CIZzKJypnN0cKxuzm-Q"><b>Obama</b> Lauds Late Sen. Byrd As=
 Being &#39;Quintessential&#39; American</a><br><font size=3D"-1"><font col=
or=3D"#777777">Wall Street Journal</font><br>By Jared A. Favole Of DOW JONE=
S NEWSWIRES WASHINGTON (Dow Jones)--President <b>Barack Obama</b> on Friday=
 praised the late Sen. Robert Byrd at a memorial service <b>...</b><br><a s=
tyle=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dht=
tp://news.google.com/news/story%3Fncl%3Dhttp://online.wsj.com/article/BT-CO=
-20100702-709057.html%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e9:p9=
:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNG6Doz3U-nM2I6bFWncl8afPG=
WlTg" title=3D"http://news.google.com/news/story?ncl=3Dhttp://online.wsj.co=
m/article/BT-CO-20100702-709057.html&amp;hl=3Den">See all stories on this t=
opic &raquo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px=
;"><a style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp=
;q=3Dhttp://www.huffingtonpost.com/2010/07/02/obama-broadband-internet-plan=
_n_634432.html&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e10:p10:t1278182161:&a=
mp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNG0uYqxq3urkrTt6JvJZMhQBlXu8Q"><b>Obama<=
/b> Announces Plan To Expand Broadband Internet Across US</a><br><font size=
=3D"-1"><font color=3D"#777777">Huffington Post (blog)</font><br>More than =
a year after Congress passed the economic stimulus package, President <b>Ba=
rack Obama</b> announced that $795 million of that money will go toward <b>=
...</b><br><a style=3D"color: #228822" href=3D"http://www.google.com/url?sa=
=3DX&amp;q=3Dhttp://news.google.com/news/story%3Fncl%3Dhttp://www.huffingto=
npost.com/2010/07/02/obama-broadband-internet-plan_n_634432.html%26hl%3Den&=
amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e10:p10:t1278182161:&amp;cd=3D4Ya67t6=
E3e4&amp;usg=3DAFQjCNENN2ossp3elIE-bpiFIGvE1Og16A" title=3D"http://news.goo=
gle.com/news/story?ncl=3Dhttp://www.huffingtonpost.com/2010/07/02/obama-bro=
adband-internet-plan_n_634432.html&amp;hl=3Den">See all stories on this top=
ic &raquo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"=
><a style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=
=3Dhttp://www.google.com/hostednews/ap/article/ALeqM5j_uiAU6uwN5XVEsj-xdaXF=
FL0ZYAD9GNE4N80&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e11:p11:t1278182161:&=
amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNE0JtAR3z5_ZY--hy1tVt6I9zdR4Q"><b>Obama=
</b> relaxing at Camp David retreat</a><br><font size=3D"-1"><font color=3D=
"#777777">The Associated Press</font><br>WASHINGTON =97 President <b>Barack=
 Obama</b> is at Camp David but will return in the evening to get ready for=
 July Fourth celebrations at the White House. <b>...</b><br><a style=3D"col=
or: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.g=
oogle.com/news/story%3Fncl%3Dhttp://www.google.com/hostednews/ap/article/AL=
eqM5j_uiAU6uwN5XVEsj-xdaXFFL0ZYAD9GNE4N80%26hl%3Den&amp;ct=3Dga&amp;cad=3D:=
s7:f1:v1:i0:lr:e11:p11:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHd=
zf8x_OMGwk__yfSaxWusmKRipw" title=3D"http://news.google.com/news/story?ncl=
=3Dhttp://www.google.com/hostednews/ap/article/ALeqM5j_uiAU6uwN5XVEsj-xdaXF=
FL0ZYAD9GNE4N80&amp;hl=3Den">See all stories on this topic &raquo;</a></fon=
t></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a style=3D"color:=
 #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://online.ws=
j.com/article/SB10001424052748704699604575343244066438822.html%3Fmod%3Dgoog=
lenews_wsj&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e12:p12:t1278182161:&amp;c=
d=3D4Ya67t6E3e4&amp;usg=3DAFQjCNE8B_NfjJXC4RHpm2M17nxYcTSPxw"><b>Obama</b> =
Dealt a Blow Over Education Initiatives</a><br><font size=3D"-1"><font colo=
r=3D"#777777">Wall Street Journal</font><br>By STEPHANIE BANCHERO President=
 <b>Barack Obama&#39;s</b> education-overhaul agenda was dealt its first ma=
jor setback after the US House of Representatives diverted <b>...</b><br><a=
 style=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://online.wsj.com/article/SB1=
0001424052748704699604575343244066438822.html%253Fmod%253Dgooglenews_wsj%26=
hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e12:p12:t1278182161:&amp;cd=
=3D4Ya67t6E3e4&amp;usg=3DAFQjCNF9MZeezqY5MgGiV4kxilYA3jd5mw" title=3D"http:=
//news.google.com/news/story?ncl=3Dhttp://online.wsj.com/article/SB10001424=
052748704699604575343244066438822.html%3Fmod%3Dgooglenews_wsj&amp;hl=3Den">=
See all stories on this topic &raquo;</a></font></td></tr><tr><td style=3D"=
padding: 0px 8px 16px 8px;"><a style=3D"color: #1111CC" href=3D"http://www.=
google.com/url?sa=3DX&amp;q=3Dhttp://www.google.com/hostednews/ap/article/A=
LeqM5hfQx49i3sKZsF3inUlP1RjmYKP6AD9GNLBJG2&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:=
i0:lt:e13:p13:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNGkw0ih4GptM=
ke1xMwYGdSC4AoKew">Analysis: On Korea trade deal, <b>Obama</b> needs GOP ai=
d</a><br><font size=3D"-1"><font color=3D"#777777">The Associated Press</fo=
nt><br>WASHINGTON =97 President <b>Barack Obama</b> wants Congress to appro=
ve a free trade deal with South Korea. Members of his own party have shown =
little enthusiasm for <b>...</b><br><a style=3D"color: #228822" href=3D"htt=
p://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%3Fn=
cl%3Dhttp://www.google.com/hostednews/ap/article/ALeqM5hfQx49i3sKZsF3inUlP1=
RjmYKP6AD9GNLBJG2%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e13:p13:t=
1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNEmp5Qv0wwUhtdQI8SjDlMH4Ktj=
kg" title=3D"http://news.google.com/news/story?ncl=3Dhttp://www.google.com/=
hostednews/ap/article/ALeqM5hfQx49i3sKZsF3inUlP1RjmYKP6AD9GNLBJG2&amp;hl=3D=
en">See all stories on this topic &raquo;</a></font></td></tr><tr><td style=
=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #1111CC" href=3D"http://=
www.google.com/url?sa=3DX&amp;q=3Dhttp://online.wsj.com/article/SB100014240=
52748704293604575342803360539416.html&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt=
:e14:p14:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNFSs07uwQ2hyzUOl6=
uniarme_AJ6g"><b>Obama</b> Says Economic Growth Is Too Slow</a><br><font si=
ze=3D"-1"><font color=3D"#777777">Wall Street Journal</font><br>By JARED A.=
 FAVOLE WASHINGTON=97President <b>Barack Obama</b> on Friday said he recogn=
izes the economy isn&#39;t growing fast enough, as a report showed job loss=
es in <b>...</b><br><a style=3D"color: #228822" href=3D"http://www.google.c=
om/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%3Fncl%3Dhttp://onli=
ne.wsj.com/article/SB10001424052748704293604575342803360539416.html%26hl%3D=
en&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e14:p14:t1278182161:&amp;cd=3D4Ya6=
7t6E3e4&amp;usg=3DAFQjCNFK_EKSr14QD07D-a6OJz8wKKjxTA" title=3D"http://news.=
google.com/news/story?ncl=3Dhttp://online.wsj.com/article/SB100014240527487=
04293604575342803360539416.html&amp;hl=3Den">See all stories on this topic =
&raquo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a=
 style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.xinhuanet.com/english2010/world/2010-07/02/c_13380724.htm&amp;c=
t=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e15:p15:t1278182161:&amp;cd=3D4Ya67t6E3e4&=
amp;usg=3DAFQjCNHXso_1mwjPHe1VaxZkdUq6GXB9lw">US House approves additional =
war funding bill</a><br><font size=3D"-1"><font color=3D"#777777">Xinhua</f=
ont><br>WASHINGTON, July 1 (Xinhua) -- The US House of Representatives on T=
hursday approved the additional war funding bill that President <b>Barack O=
bama</b> requested <b>...</b><br><a style=3D"color: #228822" href=3D"http:/=
/www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%3Fncl%=
3Dhttp://news.xinhuanet.com/english2010/world/2010-07/02/c_13380724.htm%26h=
l%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e15:p15:t1278182161:&amp;cd=3D=
4Ya67t6E3e4&amp;usg=3DAFQjCNGS6dGRl3_9fgRoSaF767F0krJkPg" title=3D"http://n=
ews.google.com/news/story?ncl=3Dhttp://news.xinhuanet.com/english2010/world=
/2010-07/02/c_13380724.htm&amp;hl=3Den">See all stories on this topic &raqu=
o;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a styl=
e=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp:=
//www.washingtonpost.com/wp-dyn/content/article/2010/07/03/AR2010070301666.=
html&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e16:p16:t1278182161:&amp;cd=3D4Y=
a67t6E3e4&amp;usg=3DAFQjCNF-Kcts3A-ssQ_fWjmZ2jw6HPYjuA">The partisan rancor=
 beneath Boehner&#39;s rhetoric</a><br><font size=3D"-1"><font color=3D"#77=
7777">Washington Post</font><br>&quot;I&#39;m not <b>Barack Obama</b> and I=
&#39;m not Nancy Pelosi,&quot; he said. &quot;I say what I mean and I mean =
what I say, and we&#39;re not going to put anything in a document that <b>.=
..</b><br><a style=3D"color: #228822" href=3D"http://www.google.com/url?sa=
=3DX&amp;q=3Dhttp://news.google.com/news/story%3Fncl%3Dhttp://www.washingto=
npost.com/wp-dyn/content/article/2010/07/03/AR2010070301666.html%26hl%3Den&=
amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e16:p16:t1278182161:&amp;cd=3D4Ya67t6=
E3e4&amp;usg=3DAFQjCNGfyBGIgbhs_SOhzLvCmB2BcxVSjA" title=3D"http://news.goo=
gle.com/news/story?ncl=3Dhttp://www.washingtonpost.com/wp-dyn/content/artic=
le/2010/07/03/AR2010070301666.html&amp;hl=3Den">See all stories on this top=
ic &raquo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"=
><a style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=
=3Dhttp://www.usatoday.com/sports/soccer/2010-07-01-3013273377_x.htm&amp;ct=
=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e17:p17:t1278182161:&amp;cd=3D4Ya67t6E3e4&a=
mp;usg=3DAFQjCNELm6RSE4zC2n7puqW5LArcgWk-HA">President <b>Obama</b> honors =
NJ&#39;s Sky Blue soccer team</a><br><font size=3D"-1"><font color=3D"#7777=
77">USA Today</font><br>By AP President <b>Barack Obama</b> saluted New Jer=
sey&#39;s Sky Blue FC women&#39;s soccer team at a White House ceremony on =
Thursday. Sky Blue earned the White House <b>...</b><br><a style=3D"color: =
#228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.googl=
e.com/news/story%3Fncl%3Dhttp://www.usatoday.com/sports/soccer/2010-07-01-3=
013273377_x.htm%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e17:p17:t12=
78182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNE_dFPAyADZb5cin_-9tga8CAGa0g=
" title=3D"http://news.google.com/news/story?ncl=3Dhttp://www.usatoday.com/=
sports/soccer/2010-07-01-3013273377_x.htm&amp;hl=3Den">See all stories on t=
his topic &raquo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16p=
x 8px;"><a style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3D=
X&amp;q=3Dhttp://www.ynetnews.com/articles/0,7340,L-3914316,00.html&amp;ct=
=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e18:p18:t1278182161:&amp;cd=3D4Ya67t6E3e4&a=
mp;usg=3DAFQjCNHbV9iFXjS4pNix8RKik9J-uvOe3Q">Report: <b>Obama</b> warned Er=
dogan of flotilla probe</a><br><font size=3D"-1"><font color=3D"#777777">Yn=
etnews</font><br>An international inquiry into the Israeli raid on the Gaza=
-bound flotilla may hurt the Turks =96 This is the message that US Presiden=
t <b>Barack Obama</b> has <b>...</b><br><a style=3D"color: #228822" href=3D=
"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story=
%3Fncl%3Dhttp://www.ynetnews.com/articles/0,7340,L-3914316,00.html%26hl%3De=
n&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e18:p18:t1278182161:&amp;cd=3D4Ya67=
t6E3e4&amp;usg=3DAFQjCNGrBUMPbPPNOSVDlkrj9jBVDaklyw" title=3D"http://news.g=
oogle.com/news/story?ncl=3Dhttp://www.ynetnews.com/articles/0,7340,L-391431=
6,00.html&amp;hl=3Den">See all stories on this topic &raquo;</a></font></td=
></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #1111=
CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www1.voanews.co=
m/english/news/arts-and-entertainment/Little-Obama-Movie-Opens-in-Indonesia=
--97656619.html&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e19:p19:t1278182161:&=
amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNH55A_cEaeTqWnHybTZ4RwMKRkMsA">&#39;Lit=
tle <b>Obama</b>&#39; Movie Opens in Indonesia</a><br><font size=3D"-1"><fo=
nt color=3D"#777777">Voice of America</font><br>A new movie titled Little O=
bama (Obama Anak Mentang), chronicling the time President <b>Barack Obama</=
b> lived in Indonesia as a boy, has opened in Jakarta. <b>...</b><br><a sty=
le=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp=
://news.google.com/news/story%3Fncl%3Dhttp://www1.voanews.com/english/news/=
arts-and-entertainment/Little-Obama-Movie-Opens-in-Indonesia--97656619.html=
%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e19:p19:t1278182161:&amp;c=
d=3D4Ya67t6E3e4&amp;usg=3DAFQjCNErlSrfsiV6Mg6hXg_GKgX038l_4Q" title=3D"http=
://news.google.com/news/story?ncl=3Dhttp://www1.voanews.com/english/news/ar=
ts-and-entertainment/Little-Obama-Movie-Opens-in-Indonesia--97656619.html&a=
mp;hl=3Den">See all stories on this topic &raquo;</a></font></td></tr><tr><=
td style=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #1111CC" href=3D=
"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.kenoshanews.com/news/o=
bama_offers_hope_11248792.html&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e20:p2=
0:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNGGbqcLU0975fRU4dsAYDtuk=
_XEgg"><b>Obama</b> offers hope</a><br><font size=3D"-1"><font color=3D"#77=
7777">Kenosha News.com</font><br>BY JOE POTENTE RACINE =97 President <b>Bar=
ack Obama</b> struck the tone of candidate <b>Barack Obama</b>, launching a=
 Wednesday town hall meeting with pointed criticism of <b>...</b><br><a sty=
le=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp=
://news.google.com/news/story%3Fncl%3Dhttp://www.kenoshanews.com/news/obama=
_offers_hope_11248792.html%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:=
e20:p20:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHicnnWN8_WapiAZt6=
fqzlqdQztwg" title=3D"http://news.google.com/news/story?ncl=3Dhttp://www.ke=
noshanews.com/news/obama_offers_hope_11248792.html&amp;hl=3Den">See all sto=
ries on this topic &raquo;</a></font></td></tr><tr><td style=3D"padding: 0p=
x 8px 16px 8px;"><table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" wi=
dth=3D"100%"><tr><td valign=3D"top"><a style=3D"color: #1111CC" href=3D"htt=
p://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.washingtonpost.com/wp-dyn/=
content/article/2010/07/01/AR2010070106405.html%3Fhpid%3Dtopnews&amp;ct=3Dg=
a&amp;cad=3D:s7:f1:v1:i0:lt:e21:p21:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;u=
sg=3DAFQjCNFk0QNgt4CsdT5H0Mhfe1MOecoTiQ">Democrats shaping battle plan agai=
nst Republicans for November</a><br><font size=3D"-1"><font color=3D"#77777=
7">Washington Post</font><br>In his first major speech on immigration as pr=
esident, President <b>Barack Obama</b> says that while the frustrations ove=
r it aren&#39;t new, Arizona&#39;s tough new <b>...</b><br><a style=3D"colo=
r: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.go=
ogle.com/news/story%3Fncl%3Dhttp://www.washingtonpost.com/wp-dyn/content/ar=
ticle/2010/07/01/AR2010070106405.html%253Fhpid%253Dtopnews%26hl%3Den&amp;ct=
=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e21:p21:t1278182161:&amp;cd=3D4Ya67t6E3e4&a=
mp;usg=3DAFQjCNGXAl7CgTEG4syCElp-hWDAZC3QMw" title=3D"http://news.google.co=
m/news/story?ncl=3Dhttp://www.washingtonpost.com/wp-dyn/content/article/201=
0/07/01/AR2010070106405.html%3Fhpid%3Dtopnews&amp;hl=3Den">See all stories =
on this topic &raquo;</a></font></td><td align=3D"center" width=3D"80" vali=
gn=3D"top"><a href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.w=
ashingtonpost.com/wp-dyn/content/article/2010/07/01/AR2010070106405.html%3F=
hpid%3Dtopnews&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:li:e21:p21:t1278182161:&a=
mp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNFk0QNgt4CsdT5H0Mhfe1MOecoTiQ"><img bord=
er=3D"0" src=3D"http://nt1.ggpht.com/news/tbn/VWlDMJjUb8kJ" alt=3D"" width=
=3D"80" height=3D"60"></a><font size=3D"-2"><br><a href=3D"http://www.googl=
e.com/url?sa=3DX&amp;q=3Dhttp://www.washingtonpost.com/wp-dyn/content/artic=
le/2010/07/01/AR2010070106405.html%3Fhpid%3Dtopnews&amp;ct=3Dga&amp;cad=3D:=
s7:f1:v1:i0:lic:e21:p21:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNF=
k0QNgt4CsdT5H0Mhfe1MOecoTiQ">Washington Post</a></font></td></tr></table></=
td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><a style=3D"color: #11=
11CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://online.wsj.co=
m/article/SB10001424052748703571704575341273913656694.html%3Fmod%3Dgooglene=
ws_wsj&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e22:p22:t1278182161:&amp;cd=3D=
4Ya67t6E3e4&amp;usg=3DAFQjCNHHlgdzz0HczzfW8RjNeARjgXmagA">Kim Strassel: The=
 <b>Obama</b> Trade Games</a><br><font size=3D"-1"><font color=3D"#777777">=
Wall Street Journal</font><br>By KIMBERLEY A. STRASSEL More than three year=
s after Democrats took the House, and more than 18 months after <b>Barack O=
bama</b> took the Oval Office, <b>...</b><br><a style=3D"color: #228822" hr=
ef=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/=
story%3Fncl%3Dhttp://online.wsj.com/article/SB10001424052748703571704575341=
273913656694.html%253Fmod%253Dgooglenews_wsj%26hl%3Den&amp;ct=3Dga&amp;cad=
=3D:s7:f1:v1:i0:lr:e22:p22:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQj=
CNHMeWwx8BxLjWqawJJsL6o2XmBlsw" title=3D"http://news.google.com/news/story?=
ncl=3Dhttp://online.wsj.com/article/SB1000142405274870357170457534127391365=
6694.html%3Fmod%3Dgooglenews_wsj&amp;hl=3Den">See all stories on this topic=
 &raquo;</a></font></td></tr><tr><td style=3D"padding: 0px 8px 16px 8px;"><=
a style=3D"color: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=
=3Dhttp://online.wsj.com/article/SB1000142405274870342600457533899185294718=
2.html%3Fmod%3Dgooglenews_wsj&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lt:e23:p23=
:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHGhAopjOTHx6YftcJIGbdgkc=
2eAg">The <b>Obama</b> Tax Trap</a><br><font size=3D"-1"><font color=3D"#77=
7777">Wall Street Journal</font><br>That was President <b>Barack Obama</b>,=
 the heretofore unknown deficit hawk, all but announcing the other day the =
tax trap that he&#39;s been laying for Republicans. <b>...</b><br><a style=
=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp:/=
/news.google.com/news/story%3Fncl%3Dhttp://online.wsj.com/article/SB1000142=
4052748703426004575338991852947182.html%253Fmod%253Dgooglenews_wsj%26hl%3De=
n&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e23:p23:t1278182161:&amp;cd=3D4Ya67=
t6E3e4&amp;usg=3DAFQjCNGKf2xM2B4PyM9VrcuoBg6XH9O7_A" title=3D"http://news.g=
oogle.com/news/story?ncl=3Dhttp://online.wsj.com/article/SB1000142405274870=
3426004575338991852947182.html%3Fmod%3Dgooglenews_wsj&amp;hl=3Den">See all =
stories on this topic &raquo;</a></font></td></tr><tr><td style=3D"padding:=
 0px 8px 16px 8px;"><a style=3D"color: #1111CC" href=3D"http://www.google.c=
om/url?sa=3DX&amp;q=3Dhttp://online.wsj.com/article/SB100014240527487042936=
04575342960139505760.html%3Fmod%3Dgooglenews_wsj&amp;ct=3Dga&amp;cad=3D:s7:=
f1:v1:i0:lt:e24:p24:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNH9KvD=
b9rNk6kVQYnOgLrbJUmwDUQ"><b>Obama</b> the Great?</a><br><font size=3D"-1"><=
font color=3D"#777777">Wall Street Journal</font><br><b>Barack Obama</b> ha=
d barely settled in office when he won a Nobel Peace Prize. Though he&#39;s=
 been in the job fewer than 18 months, liberal scholars are already <b>...<=
/b><br><a style=3D"color: #228822" href=3D"http://www.google.com/url?sa=3DX=
&amp;q=3Dhttp://news.google.com/news/story%3Fncl%3Dhttp://online.wsj.com/ar=
ticle/SB10001424052748704293604575342960139505760.html%253Fmod%253Dgooglene=
ws_wsj%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e24:p24:t1278182161:=
&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNHc6Scmt3NnEBIb8oLF4mWyOQH5uA" title=
=3D"http://news.google.com/news/story?ncl=3Dhttp://online.wsj.com/article/S=
B10001424052748704293604575342960139505760.html%3Fmod%3Dgooglenews_wsj&amp;=
hl=3Den">See all stories on this topic &raquo;</a></font></td></tr><tr><td =
style=3D"padding: 0px 8px 16px 8px;"><table cellpadding=3D"0" cellspacing=
=3D"0" border=3D"0" width=3D"100%"><tr><td valign=3D"top"><a style=3D"color=
: #1111CC" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.goog=
le.com/hostednews/afp/article/ALeqM5jxAXXUuzD_iDzLGJP5zzgxDl-dUA&amp;ct=3Dg=
a&amp;cad=3D:s7:f1:v1:i0:lt:e25:p25:t1278182161:&amp;cd=3D4Ya67t6E3e4&amp;u=
sg=3DAFQjCNG7OOUFi7-U_YDWo8WdEbHw8MgklA">Top critic blasts <b>Obama</b> &#3=
9;whining&#39;</a><br><font size=3D"-1"><font color=3D"#777777">AFP</font><=
br>WASHINGTON =97 A top Republican US lawmaker on Thursday accused Presiden=
t <b>Barack Obama</b> of &quot;whining&quot; about his critics instead of f=
ocusing on problems like <b>...</b><br><a style=3D"color: #228822" href=3D"=
http://www.google.com/url?sa=3DX&amp;q=3Dhttp://news.google.com/news/story%=
3Fncl%3Dhttp://www.google.com/hostednews/afp/article/ALeqM5jxAXXUuzD_iDzLGJ=
P5zzgxDl-dUA%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lr:e25:p25:t12781=
82161:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNFKWYKC9sJXwelWZMnvvb6myxDEXw" t=
itle=3D"http://news.google.com/news/story?ncl=3Dhttp://www.google.com/hoste=
dnews/afp/article/ALeqM5jxAXXUuzD_iDzLGJP5zzgxDl-dUA&amp;hl=3Den">See all s=
tories on this topic &raquo;</a></font></td><td align=3D"center" width=3D"8=
0" valign=3D"top"><a href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp:=
//www.google.com/hostednews/afp/article/ALeqM5jxAXXUuzD_iDzLGJP5zzgxDl-dUA&=
amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:li:e25:p25:t1278182161:&amp;cd=3D4Ya67t6=
E3e4&amp;usg=3DAFQjCNG7OOUFi7-U_YDWo8WdEbHw8MgklA"><img border=3D"0" src=3D=
"http://nt2.ggpht.com/news/tbn/gqDt5NXyHXgJ" alt=3D"" width=3D"80" height=
=3D"54"></a><font size=3D"-2"><br><a href=3D"http://www.google.com/url?sa=
=3DX&amp;q=3Dhttp://www.google.com/hostednews/afp/article/ALeqM5jxAXXUuzD_i=
DzLGJP5zzgxDl-dUA&amp;ct=3Dga&amp;cad=3D:s7:f1:v1:i0:lic:e25:p25:t127818216=
1:&amp;cd=3D4Ya67t6E3e4&amp;usg=3DAFQjCNG7OOUFi7-U_YDWo8WdEbHw8MgklA">AFP</=
a></font></td></tr></table></td></tr></table><br><hr noshade size=3D"1" col=
or=3D"#CCCCCC"><font size=3D"-1">Tip: Use quotes ("like this") around a set=
 of words in your query to match them exactly.. <a href=3D'http://www.googl=
e.com/support/websearch/bin/answer.py?answer=3D136861&hl=3Den&gl=3Dus&sourc=
e=3Dalertsmail&cd=3D4Ya67t6E3e4&cad=3D:s7:f1:v1:'>Learn more</a>.</font><br=
><br><font size=3D"-1"><a href=3D"http://www.google.com/alerts/remove?s=3DA=
B2Xq4jsDy4ienBZYuYgWbzBWQ5i6LiD5L4y8JY&hl=3Den&gl=3Dus&source=3Dalertsmail&=
cd=3D4Ya67t6E3e4&cad=3D:s7:f1:v1:">Remove</a> this alert.<br><a href=3D"htt=
p://www.google.com/alerts?hl=3Den&gl=3Dus&source=3Dalertsmail&cd=3D4Ya67t6E=
3e4&cad=3D:s7:f1:v1:">Create</a> another alert.<br><a href=3D"http://www.go=
ogle.com/alerts/manage?hl=3Den&gl=3Dus&source=3Dalertsmail&cd=3D4Ya67t6E3e4=
&cad=3D:s7:f1:v1:">Manage</a> your alerts.</font></div></body></html>