                                                                                                                                                                                                                                                              
Delivered-To: sean.fioritto@gmail.com
Received: by 10.216.157.203 with SMTP id o53cs149794wek;
        Sun, 2 May 2010 12:45:59 -0700 (PDT)
Return-Path: <3dtbdSxQKAHYaiiafYUfYlnm-hilYjfsaiiafY.Wig@alerts.bounces.google.com>
Received-SPF: pass (google.com: domain of 3dtbdSxQKAHYaiiafYUfYlnm-hilYjfsaiiafY.Wig@alerts.bounces.google.com designates 10.150.176.1 as permitted sender) client-ip=10.150.176.1;
Authentication-Results: mr.google.com; spf=pass (google.com: domain of 3dtbdSxQKAHYaiiafYUfYlnm-hilYjfsaiiafY.Wig@alerts.bounces.google.com designates 10.150.176.1 as permitted sender) smtp.mail=3dtbdSxQKAHYaiiafYUfYlnm-hilYjfsaiiafY.Wig@alerts.bounces.google.com; dkim=pass header.i=3dtbdSxQKAHYaiiafYUfYlnm-hilYjfsaiiafY.Wig@alerts.bounces.google.com
Received: from mr.google.com ([10.150.176.1])
        by 10.150.176.1 with SMTP id y1mr4593763ybe.13.1272829558334 (num_hops = 1);
        Sun, 02 May 2010 12:45:58 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=google.com; s=beta;
        h=domainkey-signature:mime-version:received:message-id:date:subject
         :from:to:content-type;
        bh=42K/INXzMud79UPLIGsZh8d7oC3rGzwWAgA/f+iQWwE=;
        b=HVY26XF4aXX6OwFQZsTAvXO5MaR2UINt4/URHoMu9FH7cVQOGci3BiSNOQypO8wM3B
         Lb9CqgwfYWXvEDWnudzg==
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=google.com; s=beta;
        h=mime-version:message-id:date:subject:from:to:content-type;
        b=LeDetmQaJLyxOMk5ybaJcZ6hFONxYdfxl1bK7diCyEh616Yk1BoCQx5tl23LslICGM
         dwI09l4yY5gKiGIWrt2w==
MIME-Version: 1.0
Received: by 10.150.176.1 with SMTP id y1mr3386733ybe.13.1272829558314; Sun, 
	02 May 2010 12:45:58 -0700 (PDT)
Message-ID: <000e0cdf164eaed76a0485a1b9c3@google.com>
Date: Sun, 02 May 2010 19:45:58 +0000
Subject: Click to confirm your Google Alert
From: Google Alerts <googlealerts-noreply@google.com>
To: sean.fioritto@gmail.com
Content-Type: text/plain; charset=ISO-8859-1; format=flowed; delsp=yes

Google received a request to start sending Alerts for the search
[ test ] to sean.fioritto@gmail.com.

Verify this Google Alert request:
http://www.google.com/alerts/verify/bad?gl=us&hl=en&s=AB2Xq4jYrbhsp8BlA12NFLDxGgFlmQQ2kF2WF5o

Cancel this Google Alert request:
http://www.google.com/alerts/remove?gl=us&hl=en&s=AB2Xq4jYrbhsp8BlA12NFLDxGgFlmQQ2kF2WF5o

Thanks,
The Google Alerts Team
http://www.google.com/alerts?gl=us&hl=en
