                                                                                                                                                                                                                                                               
Delivered-To: sean.fioritto@gmail.com
Received: by 10.14.119.201 with SMTP id n49cs10020eeh;
        Sat, 3 Jul 2010 11:20:00 -0700 (PDT)
Return-Path: <3T38vTBQKAEos00sxqmxq354-z03q1xAs00sxq.o0y@alerts.bounces.google.com>
Received-SPF: pass (google.com: domain of 3T38vTBQKAEos00sxqmxq354-z03q1xAs00sxq.o0y@alerts.bounces.google.com designates 10.100.116.12 as permitted sender) client-ip=10.100.116.12;
Authentication-Results: mr.google.com; spf=pass (google.com: domain of 3T38vTBQKAEos00sxqmxq354-z03q1xAs00sxq.o0y@alerts.bounces.google.com designates 10.100.116.12 as permitted sender) smtp.mail=3T38vTBQKAEos00sxqmxq354-z03q1xAs00sxq.o0y@alerts.bounces.google.com; dkim=pass header.i=3T38vTBQKAEos00sxqmxq354-z03q1xAs00sxq.o0y@alerts.bounces.google.com
Received: from mr.google.com ([10.100.116.12])
        by 10.100.116.12 with SMTP id o12mr606209anc.37.1278181199077 (num_hops = 1);
        Sat, 03 Jul 2010 11:19:59 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=google.com; s=beta;
        h=domainkey-signature:mime-version:received:message-id:date:subject
         :from:to:content-type;
        bh=qswEoT5rpgBOAHUDIGzeweLevWVSnq88yBmR8PRyBD0=;
        b=okz6CwPSvnK0CGcn+8rc0zGPoh5Tof7vuewSCx+YL6B543TVrUusLO4x6AnvYqg/VT
         3NtzEVj/uDfwC6eL7RVQ==
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=google.com; s=beta;
        h=mime-version:message-id:date:subject:from:to:content-type;
        b=rVNrJUeQxCJp6VG3FtQwSfkTiHftjuJgehCDmfwvCR7lWm1qfhZKEwTFIjRJqri/Du
         s492QAEwHqY5OLJ3zzJQ==
MIME-Version: 1.0
Received: by 10.100.116.12 with SMTP id o12mr427614anc.37.1278181199016; Sat, 
	03 Jul 2010 11:19:59 -0700 (PDT)
Message-ID: <0016e642d3a05375e6048a7fc0a2@google.com>
Date: Sat, 03 Jul 2010 18:19:59 +0000
Subject: Click to confirm your Google Alert
From: Google Alerts <googlealerts-noreply@google.com>
To: sean.fioritto@gmail.com
Content-Type: text/plain; charset=ISO-8859-1; format=flowed; delsp=yes

Google received a request to start sending Alerts for the search
[ barack obama ] to sean.fioritto@gmail.com.

Verify this Google Alert request:
http://www.google.com/alerts/verify/bad?gl=us&hl=en&s=AB2Xq4jsDy4ienBZYuYgWbzBWQ5i6LiD5L4y8JY

Cancel this Google Alert request:
http://www.google.com/alerts/remove?gl=us&hl=en&s=AB2Xq4jsDy4ienBZYuYgWbzBWQ5i6LiD5L4y8JY

Thanks,
The Google Alerts Team
http://www.google.com/alerts?gl=us&hl=en

This service is offered under Google's standard terms of service:  
http://www.google.com/accounts/TOS
