                                                                                                                                                                                                                                                               
Delivered-To: sean@twosix.es
Received: by 10.220.176.139 with SMTP id be11cs7625vcb;
        Sat, 29 May 2010 19:34:25 -0700 (PDT)
Received: by 10.141.187.3 with SMTP id o3mr1846700rvp.224.1275186864523;
        Sat, 29 May 2010 19:34:24 -0700 (PDT)
Return-Path: <3rs4BTBQKBMow44w1uq1u798-347u51Ew44w1u.s428uq39C48yD.u8@alerts.bounces.google.com>
Received: from mail-px0-f199.google.com (mail-px0-f199.google.com [209.85.212.199])
        by mx.google.com with ESMTP id 37si4842955pzk.127.2010.05.29.19.34.23;
        Sat, 29 May 2010 19:34:23 -0700 (PDT)
Received-SPF: pass (google.com: domain of 3rs4BTBQKBMow44w1uq1u798-347u51Ew44w1u.s428uq39C48yD.u8@alerts.bounces.google.com designates 209.85.212.199 as permitted sender) client-ip=209.85.212.199;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of 3rs4BTBQKBMow44w1uq1u798-347u51Ew44w1u.s428uq39C48yD.u8@alerts.bounces.google.com designates 209.85.212.199 as permitted sender) smtp.mail=3rs4BTBQKBMow44w1uq1u798-347u51Ew44w1u.s428uq39C48yD.u8@alerts.bounces.google.com; dkim=pass (test mode) header.i=@google.com
Received: by pxi14 with SMTP id 14so2482937pxi.6
        for <sean@twosix.es>; Sat, 29 May 2010 19:34:22 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=google.com; s=beta;
        h=domainkey-signature:mime-version:received:list-unsubscribe:list-id
         :message-id:date:subject:from:to:content-type
         :content-transfer-encoding;
        bh=K5kyCC+KyASiJLRRWYWFt/gSuzwwgz59yA8oNTclABU=;
        b=eXiPNp/ZKDi2vZywa0x+hGod3tNeVdM2KEBQ4UtYZZzO3ONLLuJzYZ1ZbvgeXZIA52
         4pCNeIawuGiajjq878kQ==
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=google.com; s=beta;
        h=mime-version:list-unsubscribe:list-id:message-id:date:subject:from
         :to:content-type:content-transfer-encoding;
        b=DxZNCP8eAyyFG0XhGi0Uka1p8m76/xUzwlLfQ0uI2A4ujrhtAJNaoSSPet/qsJT8Wk
         cLa8+DROPaeLUyelp6Pg==
MIME-Version: 1.0
Received: by 10.141.214.27 with SMTP id r27mr797847rvq.34.1275186862806; Sat, 
	29 May 2010 19:34:22 -0700 (PDT)
List-Unsubscribe: <mailto:ur@unsubscribe.alerts.google.com?subject=AB2Xq4gphDRTYccFxGDAJSiT9DpqnjXaEJSNAws>
List-Id: <AB2Xq4gphDRTYccFxGDAJSiT9DpqnjXaEJSNAws.alerts.google.com>
Message-ID: <000e0cd1b66efad5b60487c6932b@google.com>
Date: Sun, 30 May 2010 02:34:22 +0000
Subject: Google Alert - tim
From: Google Alerts <googlealerts-noreply@google.com>
To: sean@twosix.es
Content-Type: text/html; charset=windows-1252
Content-Transfer-Encoding: quoted-printable

<html><head></head><body><div style=3D"font-family: sans-serif">
<p><font size=3D"+1">Google News Alert for: <b>tim</b></font></p>
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"600"><tr><=
td style=3D"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://www.washingtonpost.com/wp-dyn/content/blog/2010/05/29/BL2010052903328=
.html&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lt:e0:p0:t1275186862:&amp;cd=3Da5m=
wqwo7e34&amp;usg=3DAFQjCNEjQiYQ7CDnl5eqAnbjt4keqtGYmw">
Strasburg live-blog: <b>Tim</b> Redding cameo edition</a><br>
<font size=3D"-1"><font color=3D"#666666">Washington Post (blog)</font><br>
Meanwhile, the Chiefs took the lead against <b>Tim</b> Redding in the botto=
m of the fourth, on RBI singles by Chase Lambin and Luis Ordaz. It&#39;s 2-=
1, Chiefs, <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://www.washingtonpost.com/wp-=
dyn/content/blog/2010/05/29/BL2010052903328.html%26hl%3Den&amp;ct=3Dga&amp;=
cad=3D:s7:f1:v0:i0:lr:e0:p0:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQ=
jCNGdHOlrxE-j4vW10rktFviOA4av7A" title=3D"http://news.google.com/news/story=
?ncl=3Dhttp://www.washingtonpost.com/wp-dyn/content/blog/2010/05/29/BL20100=
52903328.html&amp;hl=3Den">See all stories on this topic</a></font></td></t=
r><tr><td style=3D"padding-bottom:1em">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"80" align=
=3D"left" style=3D"margin-right: 10px; margin-bottom: 10px;"><tr><td align=
=3D"center"><a href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://www.=
latimes.com/sports/la-sp-baseball-down-line-20100530,0,3421685.story&amp;ct=
=3Dga&amp;cad=3D:s7:f1:v0:i0:li:e1:p1:t1275186862:&amp;cd=3Da5mwqwo7e34&amp=
;usg=3DAFQjCNHmnskmfYxGUiaAyFjF5JcIYdyuEQ"><img border=3D"0" src=3D"http://=
nt2.ggpht.com/news/tbn/wsd9ptoVrmMJ" alt=3D"" width=3D"80" height=3D"62"></=
a></td></tr><tr><td align=3D"center"><font size=3D-2><a href=3D"http://www.=
google.com/url?sa=3DX&amp;q=3Dhttp://www.latimes.com/sports/la-sp-baseball-=
down-line-20100530,0,3421685.story&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lic:e=
1:p1:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNHmnskmfYxGUiaAyFjF5J=
cIYdyuEQ">Los Angeles Times</a></font></td></tr></table>
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://www.latimes.com/sports/la-sp-baseball-down-line-20100530,0,3421685.st=
ory&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lt:e1:p1:t1275186862:&amp;cd=3Da5mwq=
wo7e34&amp;usg=3DAFQjCNHmnskmfYxGUiaAyFjF5JcIYdyuEQ">
Colorado&#39;s Ubaldo Jimenez to face San Francisco&#39;s <b>Tim</b> Lincec=
um on Memorial Day</a><br>
<font size=3D"-1"><font color=3D"#666666">Los Angeles Times</font><br>
Ubaldo Jimenez and <b>Tim</b> Lincecum meet in a Memorial Day showdown in S=
an Francisco, a coming-out party for the Colorado Rockies&#39; ace. <b>...<=
/b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://www.latimes.com/sports/la-=
sp-baseball-down-line-20100530,0,3421685.story%26hl%3Den&amp;ct=3Dga&amp;ca=
d=3D:s7:f1:v0:i0:lr:e1:p1:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjC=
NE98R81Ay_52PT2aWJm2fZe60IYfA" title=3D"http://news.google.com/news/story?n=
cl=3Dhttp://www.latimes.com/sports/la-sp-baseball-down-line-20100530,0,3421=
685.story&amp;hl=3Den">See all stories on this topic</a></font></td></tr><t=
r><td style=3D"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://www.goal.com/en-us/news/67/world-cup/2010/05/29/1948387/world-cup-201=
0-tim-howard-cautious-about-facing-rooney&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i=
0:lt:e2:p2:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNHAwzRXUnf_zeC7=
gqFWEpesHyZBYg">
World Cup 2010: <b>Tim</b> Howard Cautious About Facing Rooney</a><br>
<font size=3D"-1"><font color=3D"#666666">Goal.com</font><br>
By Andrea Canales, with reporting by Noah Davis Some might think that Ameri=
can goalkeeper <b>Tim</b> Howard would feel especially confident about faci=
ng England in <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://www.goal.com/en-us/news/67=
/world-cup/2010/05/29/1948387/world-cup-2010-tim-howard-cautious-about-faci=
ng-rooney%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lr:e2:p2:t1275186862=
:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNEncaJlA1943Kx6lIsrdd3-u36wIQ" title=
=3D"http://news.google.com/news/story?ncl=3Dhttp://www.goal.com/en-us/news/=
67/world-cup/2010/05/29/1948387/world-cup-2010-tim-howard-cautious-about-fa=
cing-rooney&amp;hl=3Den">See all stories on this topic</a></font></td></tr>=
<tr><td style=3D"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://mlb.mlb.com/news/article.jsp%3Fymd%3D20100527%26content_id%3D10521572=
%26vkey%3Dnews_mlb%26fext%3D.jsp%26c_id%3Dmlb&amp;ct=3Dga&amp;cad=3D:s7:f1:=
v0:i0:lt:e3:p3:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNH3JpPoDg2S=
zfSiWBzjUtHT5fe3aw">
Lincecum eyes success past 100th start</a><br>
<font size=3D"-1"><font color=3D"#666666">MLB.com</font><br>
By Chris Haft / MLB.com SAN FRANCISCO -- <b>Tim</b> Lincecum might be known=
 as The Freak, but he&#39;s also no fool. The Giants right-hander has susta=
ined almost <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://mlb.mlb.com/news/article.j=
sp%253Fymd%253D20100527%2526content_id%253D10521572%2526vkey%253Dnews_mlb%2=
526fext%253D.jsp%2526c_id%253Dmlb%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v0=
:i0:lr:e3:p3:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNG4a1DG52yOQO=
-z_zpKceThF-UhsQ" title=3D"http://news.google.com/news/story?ncl=3Dhttp://m=
lb.mlb.com/news/article.jsp%3Fymd%3D20100527%26content_id%3D10521572%26vkey=
%3Dnews_mlb%26fext%3D.jsp%26c_id%3Dmlb&amp;hl=3Den">See all stories on this=
 topic</a></font></td></tr><tr><td style=3D"padding-bottom:1em">
<table cellpadding=3D"0" cellspacing=3D"0" border=3D"0" width=3D"80" align=
=3D"left" style=3D"margin-right: 10px; margin-bottom: 10px;"><tr><td align=
=3D"center"><a href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dhttp://blea=
cherreport.com/articles/398426-why-you-should-root-for-tim-tebow&amp;ct=3Dg=
a&amp;cad=3D:s7:f1:v0:i0:li:e4:p4:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=
=3DAFQjCNEewREkGnmK4GDDtAiIAkhZ9SF4Gg"><img border=3D"0" src=3D"http://nt0.=
ggpht.com/news/tbn/BKUtAB-g958J" alt=3D"" width=3D"80" height=3D"55"></a></=
td></tr><tr><td align=3D"center"><font size=3D-2><a href=3D"http://www.goog=
le.com/url?sa=3DX&amp;q=3Dhttp://bleacherreport.com/articles/398426-why-you=
-should-root-for-tim-tebow&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lic:e4:p4:t12=
75186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNEewREkGnmK4GDDtAiIAkhZ9SF4Gg=
">Bleacher Report</a></font></td></tr></table>
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://bleacherreport.com/articles/398426-why-you-should-root-for-tim-tebow&=
amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lt:e4:p4:t1275186862:&amp;cd=3Da5mwqwo7e=
34&amp;usg=3DAFQjCNEewREkGnmK4GDDtAiIAkhZ9SF4Gg">
Why You Should Root For <b>Tim</b> Tebow</a><br>
<font size=3D"-1"><font color=3D"#666666">Bleacher Report</font><br>
Then there&#39;s <b>Tim</b> Tebow, the man who is more nationally despised =
than any of the aforementioned NFL-ers. Tebow has committed no crimes in hi=
s young life and <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://bleacherreport.com/article=
s/398426-why-you-should-root-for-tim-tebow%26hl%3Den&amp;ct=3Dga&amp;cad=3D=
:s7:f1:v0:i0:lr:e4:p4:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNGJV=
nrVf4FuqmusErQEQ-hNMNyeCQ" title=3D"http://news.google.com/news/story?ncl=
=3Dhttp://bleacherreport.com/articles/398426-why-you-should-root-for-tim-te=
bow&amp;hl=3Den">See all stories on this topic</a></font></td></tr><tr><td =
style=3D"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://www.associatedcontent.com/article/5432304/tim_burton_and_johnny_depps=
_alice_in.html&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lt:e5:p5:t1275186862:&amp=
;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNHuVoS_ODS9ByUf5xBk-Ddo-3UH_w">
<b>Tim</b> Burton and Johnny Depp&#39;s Alice in Wonderland Joins the Billi=
on-Dollar Club</a><br>
<font size=3D"-1"><font color=3D"#666666">Associated Content</font><br>
<b>Tim</b> Burton&#39;s re-imagining of the childhood classic Alice in Wond=
erland has reached $1 billion in worldwide sales, and ranks sixth in the to=
p-grossing films <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://www.associatedcontent.com/=
article/5432304/tim_burton_and_johnny_depps_alice_in.html%26hl%3Den&amp;ct=
=3Dga&amp;cad=3D:s7:f1:v0:i0:lr:e5:p5:t1275186862:&amp;cd=3Da5mwqwo7e34&amp=
;usg=3DAFQjCNGXkap3_9EEoLJ0NB8RbMkxO_1PAg" title=3D"http://news.google.com/=
news/story?ncl=3Dhttp://www.associatedcontent.com/article/5432304/tim_burto=
n_and_johnny_depps_alice_in.html&amp;hl=3Den">See all stories on this topic=
</a></font></td></tr><tr><td style=3D"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://news.bostonherald.com/news/politics/view/20100529tim_cahill_defends_s=
lam_vs_gov_deval_patrick_on_muslim_meet/srvc%3Dhome%26position%3Dalso&amp;c=
t=3Dga&amp;cad=3D:s7:f1:v0:i0:lt:e6:p6:t1275186862:&amp;cd=3Da5mwqwo7e34&am=
p;usg=3DAFQjCNEG4k1qC8B9pjwqzUyQ0oEBnpjd5Q">
<b>Tim</b> Cahill defends slam vs. Gov. Deval Patrick on Muslim meet</a><br=
>
<font size=3D"-1"><font color=3D"#666666">Boston Herald</font><br>
Deval Patrick&#39;s attendance at a Muslim-organized forum May 22, embattle=
d gubernatorial candidate <b>Tim</b> Cahill went on the defense yesterday, =
<b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://news.bostonherald.com/news=
/politics/view/20100529tim_cahill_defends_slam_vs_gov_deval_patrick_on_musl=
im_meet/srvc%253Dhome%2526position%253Dalso%26hl%3Den&amp;ct=3Dga&amp;cad=
=3D:s7:f1:v0:i0:lr:e6:p6:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCN=
Fx-8I05_E7QGl4r0jaHaXjDrON4w" title=3D"http://news.google.com/news/story?nc=
l=3Dhttp://news.bostonherald.com/news/politics/view/20100529tim_cahill_defe=
nds_slam_vs_gov_deval_patrick_on_muslim_meet/srvc%3Dhome%26position%3Dalso&=
amp;hl=3Den">See all stories on this topic</a></font></td></tr><tr><td styl=
e=3D"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://www.rotoworld.com/content/playerpages/playerbreakingnews.asp%3Fsport%=
3DMLB%26id%3D1756%26line%3D291809%26spln%3D1&amp;ct=3Dga&amp;cad=3D:s7:f1:v=
0:i0:lt:e7:p7:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNHnjR4-Wfp3j=
UFxJAr2zQPupSjp_Q">
<b>Tim</b> Wakefield: Wakefiled lit up for 12 hits in loss to KC</a><br>
<font size=3D"-1"><font color=3D"#666666">Rotoworld.com</font><br>
<b>Tim</b> Wakefield was lit up for 12 hits and nine earned runs over 3 2/3=
 innings Friday as the Royals lost to the Red Sox. When his knuckler isn&#3=
9;t working, <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://www.rotoworld.com/content/=
playerpages/playerbreakingnews.asp%253Fsport%253DMLB%2526id%253D1756%2526li=
ne%253D291809%2526spln%253D1%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:l=
r:e7:p7:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNH0oebbJz7ya3Mq0YW=
57MvOcyVFGQ" title=3D"http://news.google.com/news/story?ncl=3Dhttp://www.ro=
toworld.com/content/playerpages/playerbreakingnews.asp%3Fsport%3DMLB%26id%3=
D1756%26line%3D291809%26spln%3D1&amp;hl=3Den">See all stories on this topic=
</a></font></td></tr><tr><td style=3D"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://www.pe.com/localnews/stories/PE_News_Local_D_white28.eb041de.html&amp=
;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lt:e8:p8:t1275186862:&amp;cd=3Da5mwqwo7e34&=
amp;usg=3DAFQjCNF5aTU0kXztBDPH8xqIUfi-37jcrA">
UCR alumnus <b>Tim</b> White fields questions about the discovery of Ardi</=
a><br>
<font size=3D"-1"><font color=3D"#666666">Press-Enterprise</font><br>
By MARK MUCKENFUSS Paleontologist <b>Tim</b> White returned to his UC River=
side alma mater to deliver a lecture Thursday just as his fellow scientists=
 began <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://www.pe.com/localnews/stori=
es/PE_News_Local_D_white28.eb041de.html%26hl%3Den&amp;ct=3Dga&amp;cad=3D:s7=
:f1:v0:i0:lr:e8:p8:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNGUbsRa=
P4lO-Way0qTvsaFZ9Oumnw" title=3D"http://news.google.com/news/story?ncl=3Dht=
tp://www.pe.com/localnews/stories/PE_News_Local_D_white28.eb041de.html&amp;=
hl=3Den">See all stories on this topic</a></font></td></tr><tr><td style=3D=
"padding-bottom:1em">
<a style=3D"color: blue" href=3D"http://www.google.com/url?sa=3DX&amp;q=3Dh=
ttp://www.courierpress.com/news/2010/may/29/never-cast-aside-castroneves/&a=
mp;ct=3Dga&amp;cad=3D:s7:f1:v0:i0:lt:e9:p9:t1275186862:&amp;cd=3Da5mwqwo7e3=
4&amp;usg=3DAFQjCNFde3EDP11YJoe3estWq_8kjusoxw">
Never cast aside Castroneves | <b>TIM</b> ETHRIDGE COLUMN</a><br>
<font size=3D"-1"><font color=3D"#666666">Evansville Courier &amp; Press</f=
ont><br>
By <b>Tim</b> Ethridge If Helio Castroneves doesn&#39;t repeat at the India=
napolis 500 =97 and that&#39;s a big if =97 then who is most likely to take=
 the checkered flag on <b>...</b><br>
<a style=3D"color: green" href=3D"http://www.google.com/url?sa=3DX&amp;q=3D=
http://news.google.com/news/story%3Fncl%3Dhttp://www.courierpress.com/news/=
2010/may/29/never-cast-aside-castroneves/%26hl%3Den&amp;ct=3Dga&amp;cad=3D:=
s7:f1:v0:i0:lr:e9:p9:t1275186862:&amp;cd=3Da5mwqwo7e34&amp;usg=3DAFQjCNFj5W=
1gf7P_S79X3QcJtZUdFy03OA" title=3D"http://news.google.com/news/story?ncl=3D=
http://www.courierpress.com/news/2010/may/29/never-cast-aside-castroneves/&=
amp;hl=3Den">See all stories on this topic</a></font></td></tr></table><p><=
hr noshade size=3D1><font size=3D"-1">Tip: Use a plus sign (+) to match a t=
erm in your query exactly as is.</font><p><font size=3D"-1"> <nobr>
<a href=3D"http://www.google.com/alerts/remove?s=3DAB2Xq4gphDRTYccFxGDAJSiT=
9DpqnjXaEJSNAws&amp;hl=3Den&amp;gl=3Dus&amp;source=3Dalertsmail&amp;cd=3Da5=
mwqwo7e34&amp;cad=3D:s7:f1:v0:">Remove</a> this alert.
</nobr> <br><a href=3D"http://www.google.com/alerts?hl=3Den&amp;gl=3Dus&amp=
;source=3Dalertsmail&amp;cd=3Da5mwqwo7e34&amp;cad=3D:s7:f1:v0:">Create</a> =
another alert.
<br><a href=3D"http://www.google.com/alerts/manage?hl=3Den&amp;gl=3Dus&amp;=
source=3Dalertsmail&amp;cd=3Da5mwqwo7e34&amp;cad=3D:s7:f1:v0:">Manage</a> y=
our alerts.
</font></p></div></body></html>
