                                                                                                                                                                                                                                                               
Delivered-To: sean@twosix.es
Received: by 10.220.176.139 with SMTP id be11cs7594vcb;
        Sat, 29 May 2010 19:25:55 -0700 (PDT)
Received: by 10.150.172.42 with SMTP id u42mr3381339ybe.113.1275186355771;
        Sat, 29 May 2010 19:25:55 -0700 (PDT)
Return-Path: <3sswBTBQKBMwy66y3ws3w9BA-569w73Gy66y3w.u64Aws5BE6A0F.wA@alerts.bounces.google.com>
Received: from mail-yw0-f224.google.com (mail-yw0-f224.google.com [209.85.211.224])
        by mx.google.com with ESMTP id w4si11661753ybl.54.2010.05.29.19.25.54;
        Sat, 29 May 2010 19:25:54 -0700 (PDT)
Received-SPF: pass (google.com: domain of 3sswBTBQKBMwy66y3ws3w9BA-569w73Gy66y3w.u64Aws5BE6A0F.wA@alerts.bounces.google.com designates 209.85.211.224 as permitted sender) client-ip=209.85.211.224;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of 3sswBTBQKBMwy66y3ws3w9BA-569w73Gy66y3w.u64Aws5BE6A0F.wA@alerts.bounces.google.com designates 209.85.211.224 as permitted sender) smtp.mail=3sswBTBQKBMwy66y3ws3w9BA-569w73Gy66y3w.u64Aws5BE6A0F.wA@alerts.bounces.google.com; dkim=pass (test mode) header.i=@google.com
Received: by ywh21 with SMTP id 21so2020744ywh.6
        for <sean@twosix.es>; Sat, 29 May 2010 19:25:54 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=google.com; s=beta;
        h=domainkey-signature:mime-version:received:message-id:date:subject
         :from:to:content-type;
        bh=MhWbUUTbja4ovPS/O9gdG0s9mT2kbCKhOyH3GEKY0Kw=;
        b=E+VmUpNX0XSEMzxqFyGsyFjLxNLQ00r07hPZImPbLj3GAxJLETMP0NkvXKYjx4/6Bl
         PiaD4fKuabIqAjwqgNzg==
DomainKey-Signature: a=rsa-sha1; c=nofws;
        d=google.com; s=beta;
        h=mime-version:message-id:date:subject:from:to:content-type;
        b=f7nASyVZB67O6c7kpINv0i90RZZX35Xxr/gj/MW+9FKivNdTb1QXUFold8/4N1YpFD
         /AX1+l2NDNa+7R7iRu2A==
MIME-Version: 1.0
Received: by 10.90.7.36 with SMTP id 36mr1524496agg.10.1275186354357; Sat, 29 
	May 2010 19:25:54 -0700 (PDT)
Message-ID: <0016361e7edcac859d0487c675cc@google.com>
Date: Sun, 30 May 2010 02:25:54 +0000
Subject: Click to confirm your Google Alert
From: Google Alerts <googlealerts-noreply@google.com>
To: sean@twosix.es
Content-Type: text/plain; charset=ISO-8859-1; format=flowed; delsp=yes

Google received a request to start sending Alerts for the search
[ tim ] to sean@twosix.es.

Verify this Google Alert request:
http://www.google.com/alerts/verify?gl=us&hl=en&s=AB2Xq4gphDRTYccFxGDAJSiT9DpqnjXaEJSNAws

Cancel this Google Alert request:
http://www.google.com/alerts/remove?gl=us&hl=en&s=AB2Xq4gphDRTYccFxGDAJSiT9DpqnjXaEJSNAws

Thanks,
The Google Alerts Team
http://www.google.com/alerts?gl=us&hl=en

This service is offered under Google's standard terms of service:  
http://www.google.com/accounts/TOS
