from clients import alerts
from lamson.mail import MailRequest
from conf import home
import os
import re

sender = "test@localhost"
receiver = "google@localhost"

msg = MailRequest('fakepeer', sender, receiver, open(home("tests/data/emails/alert-confirmation.msg")).read())


def test_get_confirmation_url():

    """
    Scrape the confirmation url from the email.
    """
    
    body = msg.base.body
    url = alerts.get_conf_url(body)
    assert url == "/alerts/verify?gl=us&hl=en&s=AB2Xq4jYrbhsp8BlA12NFLDxGgFlmQQ2kF2WF5o"


def test_confirmed():
    """
    Test html generated by a successful confirmation
    """
    assert alerts.confirmed(open(home('tests/data/html/good-verify.html')).read())


def test_not_confirmed():
    """
    Test html generated by a failed confirmation.
    """
    assert alerts.confirmed(open(home('tests/data/html/bad-verify.html')).read()) == False
    

def test_get_raw_alert():
    """
    Given some markup that represents an alert, test
    that we get back a dictionary of key values representing
    that alert's basic data.
    """

#     raw = alerts.get_raw_alert(
    assert False


def test_get_html_stubs():
    """
    Given some html, return a list
    of html stubs that represent
    alerts.
    """
    alertsmsg = MailRequest('fakepeer', sender, "alerts-1@lookoutthere.com", open(home("tests/data/emails/beth-alerts.msg")).read())
    stubs = alerts.get_html_stubs(alertsmsg.body())
    assert len(stubs) == 15
    assert stubs[0]['title'] == "Breaking News : Beth Phoenix Is Injured, But ''THANK GOD,'' Its Not Serious"
    assert stubs[1]['byline'] == "Dallas Morning News"
    assert stubs[5]['url'] == "http://www.google.com/url?sa=X&q=http://www.newsday.com/lifestyle/books/mom-must-face-her-fears-in-quindlen-s-every-last-one-1.1898768&ct=ga&cad=:s7:f2:v0:i0:lt:e5:p5:t1273200633:&cd=TdfUlYqIXl4&usg=AFQjCNH2DrVXtQVKUfJzXG7HPzOZ-4ycTg"

    
